config/routes.rb
Rails.application.routes.draw do
  resources :locations
  get 'sessions/new'

  get 'checkings/new' => 'checkings#new', as: 'new_checking'

  resources :users
  resources :books
  resources :checkings, except: [:checking, :new]

  get "books/index" => 'books#index'
  get "books/new" => 'books#new', as: 'new'
  get "books/:id/edit" => 'books#edit'
  get "books/:id/" => "books#show"
  get "books/:id/checkingIn" => "books#checkingIn", as: 'checking_in'
  get "books/:id/checkOut/:YiBoID" => "books#checkingOut", as: 'checking_out'
  get "checking" => "books#checking", as: 'checking_book'
  get "users/:id/history" => "users#history", as: 'user_history'
  get "books/:id/history" => "books#history", as: 'book_history'
  get "/fetch_books" => 'books#fetch_books', as: 'fetch_books'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  
  post 'checkings/choose_checking' => 'checkings#checking', as: 'choose_checking'

  root "sessions#new"

end

app/models/checking.rb
class Checking < ActiveRecord::Base
	has_and_belongs_to_many :books
	belongs_to :user
end

app/controllers/checkings_controller.rb
class CheckingsController < ApplicationController
  before_action :set_checking, only: [:show, :edit, :update, :destroy]
  include SessionsHelper

  # GET /checkings
  # GET /checkings.json
  def index
    @checkings = Checking.all
  end

  # GET /checkings/1
  # GET /checkings/1.json
  def show
  end

  # GET /checkings/new
  def new
  	 @books = []
  	 @user = User.find_by(YiBoID: params[:YiBoID])
  	 #if user params exist
  	 if (@user && @user.books) 
        @user.books.each do |book|
  		    @books << book
  		  end
  	 end

  	 if(params[:YiBoNum])
  	 	@book = Book.find_by(YiBoNum: params[:YiBoNum])
  	 end

  end
  
  def checking
    @checking = Checking.create(:status => params[:status], :user_id => params[:user_id])
    book = Book.find(params[:book_id])
    @checking.books << book
    @checking.save

    if @checking.status == "in"
      book.update!(user_id: nil)
      flash[:notice] ="#{@checking.user.name}已经将#{book.title}归还"
    elsif @checking.status == "out"
      book.update!(user_id: params[:user_id])
      flash[:notice] = "图书已经被#{@checking.user.name}借出" 
    end
    
    

	  redirect_to new_checking_path
  end

  # GET /checkings/1/edit
  def edit
  end

  # POST /checkings
  # POST /checkings.json
  # def create
  #   @checking = Checking.new(checking_params)

  #   respond_to do |format|
  #     if @checking.save
  #       format.html { redirect_to "new", notice: 'Checking was successfully created.' }
  #       format.json { render :show, status: :created, location: @checking }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @checking.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def create
    @checking = Checking.create(checking_params)
    @checking.save

    if @checking.status == "in"
      @checking.books.first.update!(user_id: nil)
      flash[:notice] ="#{@checking.user.name}已经将#{@checking.books.first.title}归还"
    elsif @checking.status == "out"
      @checking.books.each do |book|
        book.update(user_id: @checking.user.id)
      end
    end

    flash[:notice] = "图书已经被#{@checking.user.name}借出" 
  end

  # PATCH/PUT /checkings/1
  # PATCH/PUT /checkings/1.json
  def update
    respond_to do |format|
      if @checking.update(checking_params)
        format.html { redirect_to @checking, notice: 'Checking was successfully updated.' }
        format.json { render :show, status: :ok, location: @checking }
      else
        format.html { render :edit }
        format.json { render json: @checking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkings/1
  # DELETE /checkings/1.json
  def destroy
    @checking.destroy
    respond_to do |format|
      format.html { redirect_to checkings_url, notice: 'Checking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checking
      @checking = Checking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checking_params
      params[:checking].require(:checking).permit(:user_id, :book, :status)
    end
end

app/helpers/checkings_helper.rb
module CheckingsHelper
end

app/views/checkings/_form.html.erb
<%= form_for(@checking) do |f| %>
  <% if @checking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checking.errors.count, "error") %> prohibited this checking from being saved:</h2>

      <ul>
      <% @checking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkings/edit.html.erb
<h1>Editing Checking</h1>

<%= render 'form' %>

<%= link_to 'Show', @checking %> |
<%= link_to 'Back', checkings_path %>

app/views/checkings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>借还记录</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>状态</th>
      <th>用户</th>
      <th>书目</th>
      <th>时间</th>
    </tr>
  </thead>

  <tbody class="table-striped">
    <% @checkings.each do |checking| %>
      <tr>
        <td>
          <% if checking.status == 'in'%>
            还书
          <% else %>
            借书
          <% end %>
        </td>
        <td><%= checking.user.name %></td>
        <td>《<%= checking.books.first.title %>》</td>
        <td><%= checking.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <a class="btn btn-default" href="/books" role="button">回到主页</a>
<div>

app/views/checkings/new.html.erb
<h1>借还</h1>
<p><%= flash[:notice]%></p>
<form class="row form-horizontal">
	<div class="form-group col-lg-4">
	   	<label class="control-label col-md-4">用户ID</label>
	    <div class="col-md-8">
	      <input type="text" class="form-control" placeholder="请输入用户ID" name="YiBoID" value='<%= params[:YiBoID]%>' size='30'/>
	    </div>
	</div>
	
	<div class="form-group col-lg-4">
	    <label class="control-label col-md-4">益博码</label>
	    <div class="col-md-8">
	      <input type="text" class="form-control" placeholder="请输入益博码" name="YiBoNum" value='<%= params[:YiBoNum]%>'/>
	    </div>
	</div>
	
	<div class="form-group col-lg-4">
	    <div class="">
	      <button type="submit" class="btn btn-default">确认</button>
	    </div>
	</div>
</form>


<div class="user-books-section row">
	<div class="user-section col-lg-2">
		<% if @user%>
			<%= render :partial => 'users/user', locals: {user: @user}%>
			<% if @user.books %>
				<% @user.books.each do |book| %>
					<%= render :partial => 'books/book_block', locals: {book: book} %>
				<% end %>
			<% end %>
		<% end %>
	</div>

	<div class="book-section col-lg-8">
		<% if @book  %>
			<%= render partial: 'books/book_block', locals: {book: @book}%>
		<% end %>
	</div>
</div>

<div>
	<% if @book && @book.user == @user%>
		<%= button_to "归还图书", 
		choose_checking_path({:book_id => @book.id, :user_id => @user.id, :status => 'in'}), 
		action: "create",
		class: "btn btn-primary" %>
	<% elsif @book && @user %>
		<%= button_to "确认借阅", 
		choose_checking_path({:book_id => @book.id, :user_id => @user.id, :status => 'out'}), 

		data: {confirm: "#{@user.name}将会借走#{@book.title}"}, class: "btn btn-primary" %>
	<% end %>
</div>

<br>

<div>
	<a class="btn btn-default" href="/checkings" role="button">历史记录</a>
<div>

<div>
	<a class="btn btn-default" href="/books" role="button">回到主页</a>
<div>

app/views/checkings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_checking_path(@checking) %> |
<%= link_to 'Back', checkings_path %>