config/routes.rb
Rails.application.routes.draw do
  resources :locations
  get 'sessions/new'

  get 'checkings/new' => 'checkings#new', as: 'new_checking'

  resources :users
  resources :books
  resources :checkings, except: [:checking, :new]

  get "books/index" => 'books#index'
  get "books/new" => 'books#new', as: 'new'
  get "books/:id/edit" => 'books#edit'
  get "books/:id/" => "books#show"
  get "books/:id/checkingIn" => "books#checkingIn", as: 'checking_in'
  get "books/:id/checkOut/:YiBoID" => "books#checkingOut", as: 'checking_out'
  get "checking" => "books#checking", as: 'checking_book'
  get "users/:id/history" => "users#history", as: 'user_history'
  get "books/:id/history" => "books#history", as: 'book_history'
  get "/fetch_books" => 'books#fetch_books', as: 'fetch_books'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  
  post 'checkings/choose_checking' => 'checkings#checking', as: 'choose_checking'

  root "sessions#new"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :books
	has_many :checkings
	has_one :manager

    has_secure_password
    serialize :auth_locations, Array
  
	EMAIL_REGEX = /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i
	validates :YiBoID, presence: true, uniqueness: true
	validates_format_of :email, :with => EMAIL_REGEX
	#validates :password, length: { in: 6..20 }

	def User.digest(string)
	  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
	  BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :history]
  #before_save :encrypt_password
  before_action :correct_user, only: [:edit, :update, :destroy]
  #after_save :clear_password
  include SessionsHelper


  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def login
  end

  def history
    @checkings = Checking.where(:user_id => @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :GovID, :address, :AuthNum, :YiBoID, :password, :password_confirmation, :email)
    end

    def encrypt_password
      if password.present?
        self.salt = BCrypt::Engine.generate_salt
        self.password = BCrypt::Engine.hash_secret(password, salt)
      end
    end

    def clear_password
      self.password = nil
    end
	 
	 def correct_user
    ##not finishde, should check if the 
	   @user = User.find(params[:id])
		flash[:danger] = "权限不足"
		redirect_to books_url unless current_user?(@user)
	 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for @user, html: {class: "form-horizontal"}  do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="form-group">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :姓名, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :益博码, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :YiBoID, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :身份证号, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :GovID, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :地址, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :权限, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.number_field :AuthNum, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :密码, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :password, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">确认</button>
        </div>
  </div>
<% end %>

  </div>
</div>

app/views/users/_user.html.erb
<h3>用户信息</h3>
<ul>
	<li>
		<p>姓名: <%= user.name%></p>
	</li>
	<li>
		<p>身份证: <%= user.GovID%></p>
	</li>
	<li>
		<p>地址: <%= user.address%></p>
	</li>
	<li>
		<p>剩余借阅权限: <%= user.AuthNum - user.books.count%></p>
	</li>
	<li>
		<p>电子邮箱: <%= user.email%></p>
	</li>
</ul>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/history.html.erb
<h3><%= @user.name%>的借阅历史</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>状态</th>
      <th>用户</th>
      <th>书目</th>
      <th>时间</th>
    </tr>
  </thead>

  <tbody class="table-striped">
    <% @checkings.each do |checking| %>
      <tr>
        <td>
          <% if checking.status == 'in'%>
            还书
          <% else %>
            借书
          <% end %>
        </td>
        <td><%= checking.user.name %></td>
        <td>《<%= checking.books.first.title %>》</td>
        <td><%= checking.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>用户列表</h1>

<%= will_paginate%>

<table class="table table-hover">
  <thead>
    <tr>
      <th>益博ID</th>
      <th>名字</th>
      <th>身份证号</th>
      <th>住址</th>
      <th>借阅权限</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.YiBoID %></td>
        <td><%= user.name %></td>
        <td><%= user.GovID %></td>
        <td><%= user.address %></td>
        <td><%= user.AuthNum %></td>
        <td><%= link_to '详细', user %></td>
        <td><%= link_to '编辑', edit_user_path(user) %></td>
        <td><%= link_to '删除用户', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate%>

<div>
  <a class="btn btn-primary" href="/users/new" role="button">新增用户</a>
  <a class="btn btn-default" href="/books" role="button">返回主页</a>
<div>

app/views/users/login.html.erb
<%= form_for(:user} do |f| %>
	
  <div class="field">
    <%= f.label :益博ID %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :密码 %></br>
    <%= f.text_field :password%>
  </div>

  <div class="actions">
    <%= f.submit "登陆"%>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>新用户</h1>

<%= render 'form' %>

<%= link_to '返回', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>姓名:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>身份证号:</strong>
  <%= @user.GovID %>
</p>

<p>
  <strong>地址:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>权限:</strong>
  <%= @user.AuthNum %>
</p>

<p>
  <strong>益博码：</strong>
  <%= @user.YiBoID%>
</p>

<p>
  <strong>已借:</strong>
  <% if @user.books %>

    <%= render partial: 'books/book_block', collection: @user.books, as: :book%>
  <% else %>
    <p>None</p>
  <% end %>
</p>

<%= link_to '借阅历史', user_history_path(@user)%>
<%= link_to '编辑', edit_user_path(@user) %>
<%= link_to '返回主页', books_path %>