config/routes.rb
Rails.application.routes.draw do
  resources :locations
  get 'sessions/new'

  get 'checkings/new' => 'checkings#new', as: 'new_checking'

  resources :users
  resources :books
  resources :checkings, except: [:checking, :new]

  get "books/index" => 'books#index'
  get "books/new" => 'books#new', as: 'new'
  get "books/:id/edit" => 'books#edit'
  get "books/:id/" => "books#show"
  get "books/:id/checkingIn" => "books#checkingIn", as: 'checking_in'
  get "books/:id/checkOut/:YiBoID" => "books#checkingOut", as: 'checking_out'
  get "checking" => "books#checking", as: 'checking_book'
  get "users/:id/history" => "users#history", as: 'user_history'
  get "books/:id/history" => "books#history", as: 'book_history'
  get "/fetch_books" => 'books#fetch_books', as: 'fetch_books'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  
  post 'checkings/choose_checking' => 'checkings#checking', as: 'choose_checking'

  root "sessions#new"

end

app/models/book.rb
class Book < ActiveRecord::Base
	include HTTParty
	belongs_to :user
	belongs_to :location
   has_and_belongs_to_many :checkings

	scope :search, ->(keyword) { where('keywords LIKE ?', "%#{keyword.downcase}%") if keyword.present? }
	scope :search_by_isbn, ->(isbn) {where('ISBN LIKE ?', "#{isbn}%") if isbn.present? }
  scope :filter_by_location, ->(location_id) {where("location_id = #{location_id}") if location_id.present?}
	scope :distinct_book, -> { group(:ISBN) }
  before_save :set_keywords, :set_YiBoNum

	api_key = '0087b8655dd56b660197293019804232'
  base_uri 'https://api.douban.com/v2/book'
  default_params apikey: api_key
  format :json

  def self.search_douban_by_isbn term
		add = "/isbn/#{term}"
    rawBook = get(add, query: {fields: "title,author,summary,isbn13,image,msg"})

    if rawBook['msg'].nil?
      book = Book.new(title: rawBook['title'], author: rawBook['author'], 
        description: rawBook['summary'], ISBN: rawBook['isbn13'], 
        image: rawBook['image'])
    else
      book = Book.new(title: "null")
    end
  end

	protected
    def set_keywords
    	word = [title, author, description].join(' ')
      self.keywords = word
    end

	 def set_YiBoNum
	 	while self.YiBoNum == ""  || self.YiBoNum.nil? do
			num = rand(9999999999)
			if Book.find_by(YiBoNum: num).nil?
				self.YiBoNum = num	
			end
		end
	 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:history, :show, :edit, :update, :destroy, :checkingIn, :checkingOut]
  before_action :set_user, only: [ :checkingIn, :checkingOut,]
  before_filter :authorize

  ##scope :distinct_book, { where("DISTINCT ISBN") }
  
  include SessionsHelper
  helper :all

  def index 
    all_books = Book.order(:title).paginate(page: params[:page], per_page: 10)
    @locations = Location.all

    if params[:searchType] == "keyword" ##search with keyword
      @books = all_books.search(params[:keyword])
    elsif params[:searchType] == "isbn" ##search with ISBN
      @books = all_books.search_by_isbn(params[:searchKey])
    elsif params[:location_id] ##filter by location
      @books = all_books.filter_by_location(params[:location_id])
    else
      @books = all_books
    end
  end

  def fetch_books
    search_hash = {}

    if params[:isbn]
      search_hash[:isbn] = params[:isbn]
    end

    if params[:title]
      search_hash[:title] = params[:title]
    end 

    if params[:author]
      search_hash[:author] = params[:author]
    end
    
    @books = Book.where(search_hash).order(:title).paginate(page: params[:page], per_page: 10)
    
    respond_to do |format|
        format.js
    end
  end

  def new
    if params[:isbn]
      @book = Book.search_douban_by_isbn(params[:isbn])
    else
      @book = Book.new
    end
  end

  def show
    /@user = @book.user /
  end

  def edit

  end

  def history
    @checkings = @book.checkings
  end

  /check in and check out /
  def checking 
      @book = Book.find_by(YiBoNum: params[:YiBoNum])
      @user = User.find_by(YiBoID: params[:YiBoID])
      if @user && @user.books.count != 0
        @borrowed_books = @user.books
      end
      if @book && @book.user
        @user = @book.user
      end
  end

  def checkingIn
    @book.update!(user_id: nil)

    flash[:notice] = "#{@user.name}已经将《#{@book.title}》归还"
    redirect_to checking_book_path
  end

  def checkingOut
    @book.update(user_id: @user.id)

    flash[:notice] = "图书已经被#{@user.name}借出"
    redirect_to checking_book_path
  end


  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to new_path, notice: "《#{@book.title}》已经被加入书库" }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: '书目信息已被更新' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
    end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: '成功删除书目' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_user
      if params[:YiBoID] 
        @user = User.find_by(YiBoID: params[:YiBoID])
      else
        @user = Book.find_by(id: params[:id]).user
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :image, :description, :ISBN, :user_id, :location_id, :YiBoNum)
    end
	 
	 def logged_in_user
	   unless logged_in?
		  flash[:danger] = "请先登入!"
		  redirect_to login_url
		end
	 end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<% cache book do %>
<div >
<ul>
	<li>
		<p><%= image_tag book.image%></p>
	</li>
	<li>
		<p>标题:<%= book.title%></p>
	</li>
	<li>
		<p>作者: <%= book.author%></p>
	</li>

	<li>
		<p>简述：<%= book.description[0, 100]%></p>
	</li>
	<li>
		<p>ISBN: <%= book.ISBN %></p>
	</li>
</ul>
<% end %>

app/views/books/_book_block.html.erb
<div class="block">
	<%= image_tag book.image%>

	<div>
		<ul>
			<li>书名： <%= book.title %></li>
			<li>作者： <%= book.author %></li>
			<li>ISBN码： <%= book.ISBN %></li>
		</ul>
	</div>
</div>

app/views/books/_books.html.erb
<% @books.each do |book| %>
  <div class="horizontal-block container">
    <div class="outer-layer row">
      <div class="book book-picture col-xs-2"> 
        <div class="picture">
          <!-- <img src=<%= book.image%> width="100px" height="150px"> -->
        </div>
      </div>

      <div class="book info col-xs-8">
        <div class="title-author">  
          <h4>《<%= book.title%>》--- <%= book.author.slice(2..-3)%></h4>
        </div>
        <div class="description">
          <p class="word">简介：<%= book.description.slice(0..200)%>...<a>（详细）</a></p>
        </div>
      </div>

      <div class="book options col-xs-2">
        <!-- button_to(name = nil, options = nil, html_options = nil, &block) -->
        <%= button_to "借阅", book_path(book), method: 'get', remote: true, class: 'btn btn-primary btn-block'%>
        <%= button_to "历史记录", book_history_path(book), method: 'get', class: 'btn btn-default btn-block'%>
        <%= button_to "删除", book_path(book), method: 'delete', data: { confirm: "是否确定要删除《#{book.title}》" }, class: 'btn btn-danger btn-block'%>
      </div>
    </div>
  </div>
<% end %>

app/views/books/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-1">

 <%= form_for book, html: {class: "form-horizontal"} do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="form-group">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-offset-2 col-sm-10">
    <% if book.image %>
      <%= image_tag book.image %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :图片链接, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :image, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :书名, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :作者, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :author, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :简介, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :ISBN码, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :ISBN, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :益博码, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :YiBoNum, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">确认</button>
        </div>
  </div>
<% end %>

  </div>
</div>

app/views/books/checking.html.erb
<h1>借还</h1>
<p><%= flash[:notice]%></p>
<form class="form-horizontal">
	<div class="form-group">
	   	<label class="col-sm-2 control-label">用户ID</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" placeholder="请输入用户ID" name="YiBoID" value='<%= params[:YiBoID]%>' size='30'/>
	    </div>
	</div>
	
	<div class="form-group">
	    <label class="col-sm-2 control-label">益博码</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" placeholder="请输入益博码" name="YiBoNum" value='<%= params[:YiBoNum]%>'/>
	    </div>
	</div>
	
	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	      <button type="submit" class="btn btn-default">确认</button>
	    </div>
	</div>


</form>


<div class="user-books-section">
	<div class="user-section">
		<% if @user%>
			<%= render :partial => 'users/user'%>
		<% end %>
	</div>

	<div class="book-section">
		<% if @borrowed_books%>
			<h5>未归还的书</h5>
			<% @borrowed_books.each do |book| %>
				<%= render partial: 'book_block', object: book, as: 'book' %>
			<% end %>
		<% end %>		
	</div>

	<div class="book-section">
		<% if @book %>
			<h5>要借阅的书</h5>
			<%= render partial: 'book_block', locals: {book: @book}%>
		<% end %>
	</div>
</div>

<div>
	<% if @borrowed_books%>
		<%= button_to "归还图书", checking_in_path({id: @borrowed_books.first.id, YiBoID: @user.YiBoID}), method: :get, class: "btn btn-primary" %>
	<% elsif @book && @user %>
		<%= button_to "确认借阅", checking_out_path({id: @book.id, YiBoID: @user.YiBoID}), method: :get, data: {confirm: "#{@user.name}将会借走#{@book.title}"}, class: "btn btn-primary"%>
	<% end %>
	<a class="btn btn-default" href="/books" role="button">回到主页</a>
</div>

app/views/books/edit.html.erb
<h1>编辑书目信息</h1>

<%= render partial: "form", locals: {book: @book} %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/fetch_books.js.erb
$("#books_grid").
	html("<%= escape_javascript(render partial: 'books', locals: { items: @books } ) %>");

app/views/books/history.html.erb
<h3>《<%= @book.title%>》的借阅历史</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>状态</th>
      <th>用户</th>
      <th>书目</th>
      <th>时间</th>
    </tr>
  </thead>

  <tbody class="table-striped">
    <% @checkings.each do |checking| %>
      <tr>
        <td>
          <% if checking.status == 'in'%>
            还书
          <% else %>
            借书
          <% end %>
        </td>
        <td><%= checking.user.name %></td>
        <td>《<%= checking.books.first.title %>》</td>
        <td><%= checking.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<p><%= flash[:danger]%></p>
<h1 class="header">书库</h1>

<form class="form-inline">
  <div class="form-group">
    <label class="control-label">搜索：</label>
  </div>

  <div class="form-group btn-group">
    <button type="button" 
            class="btn btn-default dropdown-toggle" 
            data-toggle="dropdown" 
            data-type="YiBoNum"
            aria-haspopup="true" 
            aria-expanded="false">
      <span class="text">益博码</span><span class="caret"></span>
    </button>

    <ul class="dropdown-menu">
      <li data-type="YiBoNum"><a>益博码</a></li>
      <li data-type="isbn"><a>ISBN</a></li>
      <li data-type="title"><a>书名</a></li>
      <li data-type="author"><a>作者</a></li>
      <li data-type="description"><a>内容</a></li>
      <li data-type="tags"><a>标签</a></li>
    </ul>
  </div>

  <div class="form-group search-field">
    <input type="text" class="form-control">
  </div>

  <div class="form-group">
    <button class="btn btn-primary" id="search-button" type="button" remote="true">搜索</button>
  </div>
</form>

<div class="divider"></div>

<div id="books_grid">
  <%= render 'books'%>
</div>

<%= will_paginate %>

app/views/books/new.html.erb
<h1 id="header" class="header">录入新书</h1>

<p><%= flash[:notice]%></p>

<form class="form-horizontal">
  <div>
  	<form class="form-horizontal row">
		<div class="form-group">
		   	<label class="col-lg-2 control-label">ISBN码</label>
		    <div class="col-lg-4">
		      <input type='text' class='form-control' value='<%= params[:isbn] %>' name='isbn' placeholder='isbn'/>
		    </div>
		
		    <div class="col-lg-offset-6">
		      <button type="submit" class="btn btn-default">确认</button>
		    </div>
		</div>
	</form>
  </div>
</form>

<div class="divider col-lg-6 col-lg-offset-1"></div>

<%= render partial: "form", locals: {book: @book}%>

<div>
	<a class="btn btn-primary" href="/books" role="button">回到主页</a>
<div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @book.image%>
</p>

<p>
  <strong>title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>ISBN:</strong>
  <%= @book.ISBN %>
</p>

<% if @user %>
<p>
  <strong>Owner:</strong>
  <%= link_to @user.name, @user%>
</p>
<% end %>

<%= link_to '借阅历史', book_history_path(@book)%>
<%= link_to '编辑', edit_book_path(@book) %>
<%= link_to '后退', books_path %>